/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.gui;

import fnss.functions.DB;
import fnss.functions.DocNumGenerator;
import fnss.functions.ReportGenerator;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import pos.functions.ItemController;
import pos.interfaces.Stock;
import pos.model.BillItem;
import pos.model.Item;

public class CreditCard extends javax.swing.JDialog {

    //DefaultTableModel dtm;
    String POS_ID, customer_id, user;
    Double BillTotal;
    Map<String, BillItem> billTable = new HashMap<>();
    Double paid;

    public CreditCard(String pPOS_ID, String pcustomer_id, String puser, Double pBillTotal, Map<String, BillItem> pbillTable) {
        //super(parent, modal);
        initComponents();
        // createKeybindings(jTable1);
        //  dtm = (DefaultTableModel) jTable1.gectModel();
        POS_ID = pPOS_ID;
        customer_id = pcustomer_id;
        user = puser;
        BillTotal = pBillTotal;
        billTable = pbillTable;
        paid = BillTotal;
        txtamount.setText(paid + "");
        this.setLocationRelativeTo(null);
        name.setNextFocusableComponent(c1);
        c1.setNextFocusableComponent(c2);
        c2.setNextFocusableComponent(c3);
        c3.setNextFocusableComponent(c4);
        c4.setNextFocusableComponent(month);
        month.setNextFocusableComponent(year);

//        billPanel.setSize((mainPanel.getWidth() - 30) / 3, billPanel.getHeight());
        //  jTable1.getTableHeader().setFont(new Font("Lato", Font.PLAIN, 18));
//        jTable1.getTableHeader().setSize(jTable1.getTableHeader().getWidth(), jTable1.getTableHeader().getHeight() + 50);
    }

    public CreditCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // createKeybindings(jTable1);
        //  dtm = (DefaultTableModel) jTable1.getModel();

        this.setLocationRelativeTo(parent);
        name.setNextFocusableComponent(c1);
        c1.setNextFocusableComponent(c2);
        c2.setNextFocusableComponent(c3);
        c3.setNextFocusableComponent(c4);
        c4.setNextFocusableComponent(month);
        month.setNextFocusableComponent(year);

//        billPanel.setSize((mainPanel.getWidth() - 30) / 3, billPanel.getHeight());
        //  jTable1.getTableHeader().setFont(new Font("Lato", Font.PLAIN, 18));
//        jTable1.getTableHeader().setSize(jTable1.getTableHeader().getWidth(), jTable1.getTableHeader().getHeight() + 50);
    }
    String code;
    Item Selected;
    boolean settled = false;

    boolean showDialog() {
        setVisible(true);
        return settled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblUser1 = new javax.swing.JLabel();
        billPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        topBar.setBackground(new java.awt.Color(41, 128, 185));
        topBar.setPreferredSize(new java.awt.Dimension(722, 80));
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topBarMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/close.png"))); // NOI18N
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        lblUser1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser1.setText("Credit Card");
        lblUser1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(lblUser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addGap(30, 30, 30))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(lblUser1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        billPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pay");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        billPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 136, 40));

        c1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        c1.setForeground(new java.awt.Color(51, 51, 51));
        c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c1.setText("XXX");
        c1.setToolTipText("");
        c1.setBorder(null);
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c1FocusGained(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });
        billPanel.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 86, 40));

        name.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setText("Name");
        name.setToolTipText("");
        name.setBorder(null);
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        billPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 362, 40));

        txtamount.setEditable(false);
        txtamount.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtamount.setForeground(new java.awt.Color(51, 51, 51));
        txtamount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtamount.setToolTipText("");
        txtamount.setBorder(null);
        txtamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtamountFocusGained(evt);
            }
        });
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtamountKeyReleased(evt);
            }
        });
        billPanel.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 180, 220, 40));

        c2.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        c2.setForeground(new java.awt.Color(51, 51, 51));
        c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c2.setText("XXX");
        c2.setToolTipText("");
        c2.setBorder(null);
        c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c2FocusGained(evt);
            }
        });
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c2KeyTyped(evt);
            }
        });
        billPanel.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 86, 40));

        c3.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        c3.setForeground(new java.awt.Color(51, 51, 51));
        c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c3.setText("XXX");
        c3.setToolTipText("");
        c3.setBorder(null);
        c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c3FocusGained(evt);
            }
        });
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        c3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c3KeyTyped(evt);
            }
        });
        billPanel.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 86, 40));

        c4.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        c4.setForeground(new java.awt.Color(51, 51, 51));
        c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c4.setText("XXX");
        c4.setToolTipText("");
        c4.setBorder(null);
        c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c4FocusGained(evt);
            }
        });
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        c4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c4KeyTyped(evt);
            }
        });
        billPanel.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 86, 40));

        month.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        month.setForeground(new java.awt.Color(51, 51, 51));
        month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        month.setText("M");
        month.setToolTipText("");
        month.setBorder(null);
        month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFocusGained(evt);
            }
        });
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthKeyTyped(evt);
            }
        });
        billPanel.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 86, 40));

        year.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        year.setForeground(new java.awt.Color(51, 51, 51));
        year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        year.setText("Y");
        year.setToolTipText("");
        year.setBorder(null);
        year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearFocusGained(evt);
            }
        });
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearKeyTyped(evt);
            }
        });
        billPanel.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 86, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblUserMouseClicked

    private void topBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseClicked

    }//GEN-LAST:event_topBarMouseClicked


    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        jLabel2MouseClicked(null);
    }//GEN-LAST:event_c1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    private void Proceed() {
        if (JOptionPane.showConfirmDialog(month, "Confirm Payment?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            proceedPayment("CASH");
        }
    }

    public void proceedPayment(String PaymentMethod) {
        try {
            POS_ID = new DocNumGenerator().nextVal("POS");
            BillTotal = 0.00;
            Double billItemQty = 0.00;
            paid = 0.00;
            Double balance = 0.00;
            Double discount = 0.00;
            for (Map.Entry<String, BillItem> entrySet : billTable.entrySet()) {

                String key = entrySet.getKey();
                BillItem value = entrySet.getValue();

                BillTotal += value.getTotal();
                billItemQty++;
                String sql = "INSERT INTO `pos_trans` "
                        + "(`pos_id`, `code`, `quantity`, `unit_price`, `total`, `user`) VALUES "
                        + "('" + POS_ID + "','" + value.getCode() + "'," + value.getQuantity() + "," + value.getUnit_price() + "," + value.getTotal() + ",'" + user + "')";
                System.out.println(DB.getDbCon().insert(sql));
            }
            if (PaymentMethod.equals("CARD")) {
                balance = 0.00;
            }
            String sql = "INSERT INTO `pos_master` "
                    + "(`pos_id`, `customer_id`, `itemcount`, `total`, `paid`, `balance`, `discount`,`payMethod`) VALUES "
                    + "('" + POS_ID + "','" + customer_id + "'," + billTable.size() + "," + BillTotal + "," + paid + "," + balance + "," + discount + ",'" + PaymentMethod + "')";
            System.out.println(DB.getDbCon().insert(sql));
            Map map = new HashMap();
            map.put("pos_id", POS_ID);
            new ReportGenerator().printReport("MainBill", map);
            POS_ID = "";
            billTable = new HashMap<>();
            BillTotal = 0.00;
            POS_MainFrame1.settled = true;
            settled = true;
            //resetAllFields();
        } catch (SQLException ex) {
            Logger.getLogger(POS_MainFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased

    }//GEN-LAST:event_jPanel1KeyReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_formMouseDragged
    int x, y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void c1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyReleased
        validateInte(evt);
    }//GEN-LAST:event_c1KeyReleased
    private void validateInte(java.awt.event.KeyEvent evt) {
        char ch = evt.getKeyChar();
        if (!(Character.isDigit(ch))) {
            evt.consume();
        }
    }

    private void validateLetter(java.awt.event.KeyEvent evt) {
        char ch = evt.getKeyChar();
        if (!(Character.isLetter(ch))) {
            evt.consume();
        }
    }

    private void digit(JTextField tf, int count, KeyEvent evt) {
        if (tf.getText().length() >= count) {
            evt.consume();
            tf.getNextFocusableComponent().requestFocus();
        }
    }

    private void c1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusGained
        c1.selectAll();
        c1.setText("");
    }//GEN-LAST:event_c1FocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.selectAll();
    }//GEN-LAST:event_nameFocusGained

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void txtamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountFocusGained

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void txtamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountKeyReleased

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
        digit(c1, 4, evt);
        validateInte(evt);// TODO add your handling code here:
    }//GEN-LAST:event_c1KeyTyped

    private void c2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2FocusGained
        c2.selectAll();
        c2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_c2FocusGained

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c2KeyReleased

    private void c2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyTyped
        digit(c2, 4, evt);
        validateInte(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_c2KeyTyped

    private void c3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c3FocusGained
        c3.selectAll();
        c3.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_c3FocusGained

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c3KeyReleased

    private void c3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyTyped
        digit(c3, 4, evt);
        validateInte(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_c3KeyTyped

    private void c4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c4FocusGained
        c4.selectAll();
        c4.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_c4FocusGained

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c4KeyReleased

    private void c4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c4KeyTyped
        digit(c4, 4, evt);
        validateInte(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_c4KeyTyped

    private void monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFocusGained

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void monthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_monthKeyReleased

    private void monthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyTyped
        digit(month, 2, evt);
        validateLetter(evt);  // TODO add your handling code here:
    }//GEN-LAST:event_monthKeyTyped

    private void yearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFocusGained

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        jLabel2MouseClicked(new MouseEvent(month, x, x, x, x, x, x, rootPaneCheckingEnabled));              // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void yearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_yearKeyReleased

    private void yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyTyped
        digit(year, 2, evt);
        validateLetter(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_yearKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        validateLetter(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped
    private void createKeybindings(JTable table) {
        table.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "Enter");
        table.getActionMap().put("Enter", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                // doubleclicked();
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreditCard dialog = new CreditCard(new javax.swing.JFrame(), true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JPanel topBar;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
