/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.gui;

import fnss.functions.DB;
import fnss.functions.DocNumGenerator;
import fnss.functions.ReportGenerator;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import pos.functions.ItemController;
import pos.interfaces.Stock;
import pos.model.BillItem;
import pos.model.Item;

/**
 *
 * @author Nisal
 */
public class POS_MainFrame1 extends javax.swing.JFrame {

    private static String user = "Nisal";
    private static String POS_ID;
    DefaultTableModel dtm;

    public POS_MainFrame1() {

        try {
            initComponents();
            txtItemCode.requestFocus();
            dtm = (DefaultTableModel) jTable1.getModel();
            //lblTime.setText(new DocNumGenerator().curVal("POS"));
            ItemController.getAllItemsFromDB();
            this.setLocationRelativeTo(null);
            this.setExtendedState(MAXIMIZED_BOTH);
            lblDate.setText(new SimpleDateFormat("dd/MM/YYYY").format(System.currentTimeMillis()));
            lblDate1.setText(new SimpleDateFormat("hh:mm:ss a").format(System.currentTimeMillis()));
            new Timer(1000, (ActionEvent e) -> {
                try {
                    lblDate1.setText(new SimpleDateFormat("hh:mm:ss a").format(System.currentTimeMillis()));
                    int hour = Calendar.getInstance().get(Calendar.HOUR_OF_DAY);
                    String greeting;
                    if (hour < 10) {
                        greeting = "Good Morning, " + user;
                    } else if (hour < 16) {
                        greeting = "Good Day, " + user;
                    } else {
                        greeting = "Good Evening, " + user;
                    }
                    lblUser1.setText(greeting);
                    // System.out.println("DB Connection Check - " + 
                    DB.getDbCon().query("SELECT 1").next();//);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage() + "\nOK to Check the Connection. Communication Failure Exits the System.");
                    DB.db = null;
                    //Logger.getLogger(POS_MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }).start();

            billPanel.setSize((mainPanel.getWidth() - 30) / 3, billPanel.getHeight());
            itemPanel.setSize((mainPanel.getWidth() - 30) / 3, itemPanel.getHeight());
            jTable1.getTableHeader().setFont(new Font("Lato", Font.PLAIN, 18));
            jTable1.getTableHeader().setSize(jTable1.getTableHeader().getWidth(), jTable1.getTableHeader().getHeight() + 50);
            loadItemButtons();
        } catch (SQLException ex) {
            Logger.getLogger(POS_MainFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblUser1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        billPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtItemCode = new javax.swing.JTextField();
        btnItemSearch = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        itemPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tabPanel = new javax.swing.JPanel();
        panelRecent = new javax.swing.JPanel();
        panelMainCat = new javax.swing.JPanel();
        panelSubCat = new javax.swing.JPanel();
        panelItem = new javax.swing.JPanel();
        headerpanel = new javax.swing.JPanel();
        btnRecent = new javax.swing.JLabel();
        btnMainCat = new javax.swing.JLabel();
        btnSUbCat = new javax.swing.JLabel();
        btnItem = new javax.swing.JLabel();
        pricingPanel1 = new javax.swing.JPanel();
        pricingPanel2 = new javax.swing.JPanel();
        txtDiscount = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        pricingPanel3 = new javax.swing.JPanel();
        btnPost = new javax.swing.JLabel();
        btnCreditCard = new javax.swing.JLabel();
        btnCash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        topBar.setBackground(new java.awt.Color(41, 128, 185));
        topBar.setPreferredSize(new java.awt.Dimension(722, 80));
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topBarMouseClicked(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText(" ");

        lblDate.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText(" ");
        lblDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDateMouseClicked(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/close.png"))); // NOI18N
        lblClose.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblUser1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser1.setText(" ");
        lblUser1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDate1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblDate1.setForeground(new java.awt.Color(255, 255, 255));
        lblDate1.setText(" ");
        lblDate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDate1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1466, Short.MAX_VALUE)
                .addComponent(lblUser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addGap(30, 30, 30))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblDate)
                    .addComponent(lblClose)
                    .addComponent(lblUser1)
                    .addComponent(lblDate1))
                .addContainerGap())
        );

        mainPanel.setOpaque(false);

        billPanel.setDoubleBuffered(false);
        billPanel.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setToolTipText("");
        txtTotal.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Total :");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jTable1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty.", "Unit Price", "Total", "  X"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(26);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        txtItemCode.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtItemCode.setForeground(new java.awt.Color(204, 204, 204));
        txtItemCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemCode.setText("Item Code");
        txtItemCode.setToolTipText("");
        txtItemCode.setBorder(null);
        txtItemCode.setNextFocusableComponent(txtPaid);
        txtItemCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemCodeFocusGained(evt);
            }
        });
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        btnItemSearch.setBackground(new java.awt.Color(52, 152, 219));
        btnItemSearch.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnItemSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnItemSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnItemSearch.setText("Search");
        btnItemSearch.setOpaque(true);
        btnItemSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItemSearchMouseClicked(evt);
            }
        });

        txtQty.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtQty.setForeground(new java.awt.Color(204, 204, 204));
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.setText("Qty");
        txtQty.setToolTipText("");
        txtQty.setBorder(null);
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
        });
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(52, 152, 219));
        btnAdd.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd.setText("Add");
        btnAdd.setOpaque(true);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(204, 204, 204));
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrice.setText("Price");
        txtPrice.setToolTipText("");
        txtPrice.setBorder(null);
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
        });
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        itemPanel.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setText("Customer");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabPanel.setLayout(new java.awt.CardLayout());

        panelRecent.setBackground(new java.awt.Color(89, 171, 227));
        panelRecent.setLayout(new java.awt.GridLayout(1, 0));
        tabPanel.add(panelRecent, "recent");

        panelMainCat.setBackground(new java.awt.Color(65, 131, 215));

        javax.swing.GroupLayout panelMainCatLayout = new javax.swing.GroupLayout(panelMainCat);
        panelMainCat.setLayout(panelMainCatLayout);
        panelMainCatLayout.setHorizontalGroup(
            panelMainCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMainCatLayout.setVerticalGroup(
            panelMainCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabPanel.add(panelMainCat, "mainCat");

        panelSubCat.setBackground(new java.awt.Color(68, 108, 179));

        javax.swing.GroupLayout panelSubCatLayout = new javax.swing.GroupLayout(panelSubCat);
        panelSubCat.setLayout(panelSubCatLayout);
        panelSubCatLayout.setHorizontalGroup(
            panelSubCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSubCatLayout.setVerticalGroup(
            panelSubCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabPanel.add(panelSubCat, "subCat");

        panelItem.setBackground(new java.awt.Color(3, 0, 131));

        javax.swing.GroupLayout panelItemLayout = new javax.swing.GroupLayout(panelItem);
        panelItem.setLayout(panelItemLayout);
        panelItemLayout.setHorizontalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        panelItemLayout.setVerticalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        tabPanel.add(panelItem, "item");

        headerpanel.setBackground(new java.awt.Color(255, 255, 255));
        headerpanel.setLayout(new java.awt.GridLayout(1, 0));

        btnRecent.setBackground(new java.awt.Color(89, 171, 227));
        btnRecent.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnRecent.setForeground(new java.awt.Color(255, 255, 255));
        btnRecent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecent.setText("Recent");
        btnRecent.setOpaque(true);
        btnRecent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecentMouseClicked(evt);
            }
        });
        headerpanel.add(btnRecent);

        btnMainCat.setBackground(new java.awt.Color(65, 131, 215));
        btnMainCat.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnMainCat.setForeground(new java.awt.Color(255, 255, 255));
        btnMainCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMainCat.setText("Main Category");
        btnMainCat.setOpaque(true);
        btnMainCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMainCatMouseClicked(evt);
            }
        });
        headerpanel.add(btnMainCat);

        btnSUbCat.setBackground(new java.awt.Color(68, 108, 179));
        btnSUbCat.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnSUbCat.setForeground(new java.awt.Color(255, 255, 255));
        btnSUbCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSUbCat.setText("Sub Category");
        btnSUbCat.setOpaque(true);
        btnSUbCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSUbCatMouseClicked(evt);
            }
        });
        headerpanel.add(btnSUbCat);

        btnItem.setBackground(new java.awt.Color(3, 0, 131));
        btnItem.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnItem.setForeground(new java.awt.Color(255, 255, 255));
        btnItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnItem.setText("Items");
        btnItem.setOpaque(true);
        btnItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItemMouseClicked(evt);
            }
        });
        headerpanel.add(btnItem);

        pricingPanel2.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        txtDiscount.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(204, 204, 204));
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.setText("%");
        txtDiscount.setBorder(null);
        txtDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscountFocusGained(evt);
            }
        });
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscountKeyTyped(evt);
            }
        });
        pricingPanel2.add(txtDiscount);

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtBalance.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(204, 204, 204));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBalance.setText("Balance");
        txtBalance.setBorder(null);
        pricingPanel2.add(txtBalance);

        txtPaid.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        txtPaid.setForeground(new java.awt.Color(204, 204, 204));
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaid.setText("Paid");
        txtPaid.setBorder(null);
        txtPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaidFocusGained(evt);
            }
        });
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaidKeyTyped(evt);
            }
        });
        pricingPanel2.add(txtPaid);

        pricingPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        btnPost.setBackground(new java.awt.Color(52, 152, 219));
        btnPost.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 255));
        btnPost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPost.setText("Post Bill");
        btnPost.setOpaque(true);
        pricingPanel3.add(btnPost);

        btnCreditCard.setBackground(new java.awt.Color(52, 152, 219));
        btnCreditCard.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnCreditCard.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreditCard.setText("Credit Card");
        btnCreditCard.setOpaque(true);
        pricingPanel3.add(btnCreditCard);

        btnCash.setBackground(new java.awt.Color(52, 152, 219));
        btnCash.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        btnCash.setForeground(new java.awt.Color(255, 255, 255));
        btnCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCash.setText("Cash Proceed");
        btnCash.setOpaque(true);
        btnCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCashMouseClicked(evt);
            }
        });
        pricingPanel3.add(btnCash);

        javax.swing.GroupLayout pricingPanel1Layout = new javax.swing.GroupLayout(pricingPanel1);
        pricingPanel1.setLayout(pricingPanel1Layout);
        pricingPanel1Layout.setHorizontalGroup(
            pricingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pricingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pricingPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pricingPanel1Layout.setVerticalGroup(
            pricingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricingPanel1Layout.createSequentialGroup()
                .addComponent(pricingPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pricingPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pricingPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pricingPanel2, pricingPanel3});

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pricingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(pricingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(itemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1924, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x, y;
    boolean tweak = false;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (tweak) {
            this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
        }
    }//GEN-LAST:event_formMouseDragged

    private void loadItemButtons() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(3, 2));
        JButton[] buttons = new JButton[Stock.items.size()];
        JPanel buttonPanel = new JPanel(new FlowLayout());
        int i = 0;
        for (Map.Entry<String, Item> entrySet : Stock.items.entrySet()) {
            String key = entrySet.getKey();
            Item value = entrySet.getValue();
            buttons[i] = new JButton();
            buttons[i].setName(key);
            buttons[i].setText(value.getName());
            panel.add(buttons[i]);
        }
    }

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        close();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void lblDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateMouseClicked
        if (evt.getClickCount() == 3) {
            tweak = !tweak;
            if (tweak) {
                lblDate.setForeground(Color.BLACK);
            } else {
                lblDate.setForeground(Color.WHITE);
            }
        }


    }//GEN-LAST:event_lblDateMouseClicked

    private void topBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseClicked
        if (evt.getClickCount() == 2) {
            this.setExtendedState(MAXIMIZED_BOTH);//this.setLocation(0,0);
        }

    }//GEN-LAST:event_topBarMouseClicked

    public void setItemCode(String itemcode) {
        txtItemCode.setText(itemcode);
    }
    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        if (Stock.items.containsKey(txtItemCode.getText()) && Stock.items.get(txtItemCode.getText()).getQuantity() > 0) {
            currentItem = Stock.items.get(txtItemCode.getText());
            loadCurrentItemtoField();
        } else {
            JOptionPane.showMessageDialog(this, "Item Not Found or Not Available on Stocks!");
            resetTextFields();
            btnItemSearchMouseClicked(null);
        }
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        btnAddMouseClicked(null);
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        btnAddMouseClicked(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_formKeyReleased

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased

    }//GEN-LAST:event_jPanel1KeyReleased

    private void txtItemCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemCodeFocusGained
        txtItemCode.selectAll();
    }//GEN-LAST:event_txtItemCodeFocusGained

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        txtQty.selectAll();
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        txtPrice.selectAll();
    }//GEN-LAST:event_txtPriceFocusGained

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        BillItem newItem = new BillItem();
        newItem.setCode(txtItemCode.getText());
        newItem.setQuantity(Double.parseDouble("0" + txtQty.getText()));
        newItem.setName(Stock.items.get(newItem.getCode()).getName());
        newItem.setUnit_price(Double.parseDouble(txtPrice.getText().replaceAll("LKR.", "").trim()));
        newItem.setSub_cat(Stock.items.get(newItem.getCode()).getSub_cat());
        System.out.println("New Item " + newItem.getCode());
        addItemToBillTable(newItem);
        resetTextFields();
        refreshTable();
    }//GEN-LAST:event_btnAddMouseClicked
    private void resetTextFields() {

        txtItemCode.requestFocus();
        txtItemCode.setText("Item Code");
        txtItemCode.setForeground(Color.GRAY);
        txtQty.setText("Qty");
        txtQty.setForeground(Color.GRAY);
        txtPrice.setText("Price");
        txtPrice.setForeground(Color.GRAY);
        txtItemCode.selectAll();
    }

    private void resetAllFields() {
        dtm.setRowCount(0);
        txtPaid.setText("Paid");
        txtTotal.setText("");
        txtBalance.setText("Balance");
        resetTextFields();
    }

    private void addItemToBillTable(BillItem item) {
        System.out.println(item.getCode());
        System.out.println(item.getName());
        System.out.println(item.getQuantity());
        System.out.println(item.getTotal());
        System.out.println(item.getUnit_price());
        if (billTable.containsKey(item.getCode() + new DecimalFormat("##.00").format(item.getUnit_price()))) {
            BillItem existingItem = billTable.get(item.getCode() + new DecimalFormat("##.00").format(item.getUnit_price()));
            // JOptionPane.showMessageDialog(null, "Item Already Added");
            existingItem.setQuantity(existingItem.getQuantity() + item.getQuantity());

        } else {
            billTable.put(item.getCode() + new DecimalFormat("##.00").format(item.getUnit_price()), item);
        }

    }
    double BillTotal = 0.00;

    private void refreshTable() {
        dtm.setRowCount(0);
        BillTotal = 0.00;
        for (Map.Entry<String, BillItem> entrySet : billTable.entrySet()) {
            BillItem item = entrySet.getValue();
            dtm.addRow(new Object[]{item.getCode(), item.getName(), item.getQuantity(), new DecimalFormat("##.00").format(item.getUnit_price()), new DecimalFormat("###,###.00").format(item.getTotal()), "  X"});
            BillTotal += item.getTotal();
        }
        txtTotal.setText("LKR. " + new DecimalFormat("###,###.00").format(BillTotal));
        txtPaid.setText(new DecimalFormat("###,###.00").format(BillTotal));
        txtBalance.setText("0.00");
    }

    private void loadCurrentItemtoField() {
        if (currentItem != null) {
            txtItemCode.setText(currentItem.getCode());
            txtItemCode.setForeground(Color.BLACK);
            txtQty.setText("1");
            txtQty.setForeground(Color.BLACK);
            txtPrice.setText("LKR. " + new DecimalFormat("#.00").format(currentItem.getSelling_price()));
            txtPrice.setForeground(Color.BLACK);
            txtQty.requestFocus();
            txtQty.selectAll();
        } else {
            resetTextFields();
        }
    }
    Item currentItem = null;
    Map<String, BillItem> billTable = new HashMap<>();
    private void btnItemSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItemSearchMouseClicked

        ItemSearch itemSearch = new ItemSearch(this, true);
        itemSearch.setLocationRelativeTo(this);
        currentItem = itemSearch.showDialog();
        loadCurrentItemtoField();

    }//GEN-LAST:event_btnItemSearchMouseClicked

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased

    }//GEN-LAST:event_txtPriceKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnRecentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecentMouseClicked
        openPanel("recent");
    }//GEN-LAST:event_btnRecentMouseClicked

    private void btnMainCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainCatMouseClicked
        openPanel("mainCat");
    }//GEN-LAST:event_btnMainCatMouseClicked

    private void btnSUbCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSUbCatMouseClicked
        openPanel("subCat");
    }//GEN-LAST:event_btnSUbCatMouseClicked

    private void btnItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItemMouseClicked
        openPanel("item");
    }//GEN-LAST:event_btnItemMouseClicked

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        if (evt.getKeyChar() > 0 && evt.getKeyChar() < 9) {
            System.out.println("num");
        }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped

    }//GEN-LAST:event_txtPriceKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedColumn() == 5 && evt.getClickCount() == 2) {
            String key = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString() + jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            System.out.println(key);
            billTable.remove(key);
            System.out.println(key);
            System.out.println(billTable);
            refreshTable();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashMouseClicked
        if (jTable1.getRowCount() != 0) {
            lblTime.setText("");
            proceedPayment("CASH");
        } else {
            errorMsg("No Items in Bill");
        }
    }//GEN-LAST:event_btnCashMouseClicked

    private void lblDate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDate1MouseClicked

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        btnCashMouseClicked(null);
    }//GEN-LAST:event_txtPaidActionPerformed

    private void txtPaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyTyped
        if (evt.getKeyChar() == 'd') {
            txtDiscount.requestFocus();
            txtDiscount.selectAll();
        }
        validateDouble(evt);
    }//GEN-LAST:event_txtPaidKeyTyped

    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased

        txtBalance.setText("" + (Double.parseDouble("0" + txtPaid.getText().replaceAll(",", "")) - BillTotal));
    }//GEN-LAST:event_txtPaidKeyReleased

    private void txtPaidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusGained
        txtPaid.selectAll();    }//GEN-LAST:event_txtPaidFocusGained

    private void txtDiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyTyped
        validateDouble(evt);    }//GEN-LAST:event_txtDiscountKeyTyped

    private void txtDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountFocusGained
        txtDiscount.selectAll();
    }//GEN-LAST:event_txtDiscountFocusGained

    private void errorMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void infoMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    public String customer_id = "";

    private void proceedPayment(String PaymentMethod) {
        try {
            POS_ID = new DocNumGenerator().nextVal("POS");
            BillTotal = 0.00;
            Double billItemQty = 0.00;
            Double paid = Double.parseDouble("0" + txtPaid.getText().replaceAll(",", ""));
            Double balance = Double.parseDouble("0" + txtBalance.getText().replaceAll(",", ""));
            Double discount = Double.parseDouble("0" + txtDiscount.getText().replaceAll("%", "").replaceAll(",", ""));
            for (Map.Entry<String, BillItem> entrySet : billTable.entrySet()) {

                String key = entrySet.getKey();
                BillItem value = entrySet.getValue();

                BillTotal += value.getTotal();
                billItemQty++;
                String sql = "INSERT INTO `pos_trans` "
                        + "(`pos_id`, `code`, `quantity`, `unit_price`, `total`, `user`) VALUES "
                        + "('" + POS_ID + "','" + value.getCode() + "'," + value.getQuantity() + "," + value.getUnit_price() + "," + value.getTotal() + ",'" + user + "')";
                System.out.println(DB.getDbCon().insert(sql));
            }
            if (PaymentMethod.equals("CARD")) {
                balance = 0.00;
            }
            String sql = "INSERT INTO `pos_master` "
                    + "(`pos_id`, `customer_id`, `itemcount`, `total`, `paid`, `balance`, `discount`,`payMethod`) VALUES "
                    + "('" + POS_ID + "','" + customer_id + "'," + billTable.size() + "," + BillTotal + "," + paid + "," + balance + "," + discount + ",'" + PaymentMethod + "')";
            System.out.println(DB.getDbCon().insert(sql));
            infoMsg(POS_ID + " is Successfully Settled!\n Bill Printing...");
            Map map = new HashMap();
            map.put("pos_id", POS_ID);
            new ReportGenerator().printReport("MainBill", map);
            POS_ID = "";
            billTable = new HashMap<>();
            BillTotal = 0.00;

            resetAllFields();
        } catch (SQLException ex) {
            Logger.getLogger(POS_MainFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void validateDouble(java.awt.event.KeyEvent evt) {
        char ch = evt.getKeyChar();
        if (!(Character.isDigit(ch) || (ch == '.'))) {
            evt.consume();
        }
    }

    private void openPanel(String Name) {
        CardLayout cardLayout = (CardLayout) (tabPanel.getLayout());
        cardLayout.show(tabPanel, Name);
    }

    private void close() {
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") == JOptionPane.OK_OPTION) {
            this.dispose();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS_MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS_MainFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnCash;
    private javax.swing.JLabel btnCreditCard;
    private javax.swing.JLabel btnItem;
    private javax.swing.JLabel btnItemSearch;
    private javax.swing.JLabel btnMainCat;
    private javax.swing.JLabel btnPost;
    private javax.swing.JLabel btnRecent;
    private javax.swing.JLabel btnSUbCat;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelItem;
    private javax.swing.JPanel panelMainCat;
    private javax.swing.JPanel panelRecent;
    private javax.swing.JPanel panelSubCat;
    private javax.swing.JPanel pricingPanel1;
    private javax.swing.JPanel pricingPanel2;
    private javax.swing.JPanel pricingPanel3;
    private javax.swing.JPanel tabPanel;
    private javax.swing.JPanel topBar;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
