package tms.gui;

import fnss.functions.DB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author afkii
 */
public class TMS_addUpdateVehicle extends javax.swing.JFrame {

    /**
     * Creates new form tmsNewHire
     */
    public TMS_addUpdateVehicle() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public TMS_addUpdateVehicle(JFrame ui) {
        parentUI = ui;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    JFrame parentUI;

    //close button function
    private void close() {
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") == JOptionPane.OK_OPTION) {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        functionImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        contentArea = new javax.swing.JPanel();
        whiteArea = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        capacityTxt = new javax.swing.JTextField();
        currentMilateTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vehicleAvailabilityTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hourlyRateTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dailyRateTxt = new javax.swing.JTextField();
        lblDeleteButton = new javax.swing.JLabel();
        vehicleNumberTxt = new javax.swing.JTextField();
        lblUpdateButton = new javax.swing.JLabel();
        lblAddButton = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        exitButton = new javax.swing.JPanel();
        exitButtonLable = new javax.swing.JLabel();
        backButton = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        blueStrip = new javax.swing.JPanel();
        lblBlueStrip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        functionImage.setOpaque(false);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/gui/images/tanker 95 x 95.png"))); // NOI18N

        javax.swing.GroupLayout functionImageLayout = new javax.swing.GroupLayout(functionImage);
        functionImage.setLayout(functionImageLayout);
        functionImageLayout.setHorizontalGroup(
            functionImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionImageLayout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(lblImage)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        functionImageLayout.setVerticalGroup(
            functionImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionImageLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        jLayeredPane1.add(functionImage);

        contentArea.setOpaque(false);

        whiteArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Clarendon Blk BT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 71, 71));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vehicle");

        jLabel3.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 71, 71));
        jLabel3.setText("Vehicle Reg. Number");

        jLabel4.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 71, 71));
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 71, 71));
        jLabel5.setText("Capacity");

        jLabel9.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 71, 71));
        jLabel9.setText("Current Milage");

        jLabel13.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(71, 71, 71));
        jLabel13.setText("Availability");

        vehicleAvailabilityTxt.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(71, 71, 71));
        jLabel14.setText("Hourly Rate");

        jLabel15.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(71, 71, 71));
        jLabel15.setText("Daily Rate");

        lblDeleteButton.setBackground(new java.awt.Color(0, 153, 153));
        lblDeleteButton.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        lblDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        lblDeleteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteButton.setText("Delete");
        lblDeleteButton.setOpaque(true);
        lblDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDeleteButtonMouseReleased(evt);
            }
        });

        lblUpdateButton.setBackground(new java.awt.Color(231, 76, 60));
        lblUpdateButton.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        lblUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateButton.setText("Update");
        lblUpdateButton.setOpaque(true);
        lblUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblUpdateButtonMouseReleased(evt);
            }
        });

        lblAddButton.setBackground(new java.awt.Color(231, 76, 60));
        lblAddButton.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        lblAddButton.setForeground(new java.awt.Color(255, 255, 255));
        lblAddButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddButton.setText("Add");
        lblAddButton.setOpaque(true);
        lblAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddButtonMouseReleased(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuel Tanker", "Oil Tanker" }));

        javax.swing.GroupLayout whiteAreaLayout = new javax.swing.GroupLayout(whiteArea);
        whiteArea.setLayout(whiteAreaLayout);
        whiteAreaLayout.setHorizontalGroup(
            whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whiteAreaLayout.createSequentialGroup()
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whiteAreaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(lblDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(whiteAreaLayout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(whiteAreaLayout.createSequentialGroup()
                                    .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(42, 42, 42)
                                    .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(capacityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentMilateTxt)
                                        .addComponent(vehicleNumberTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(whiteAreaLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(106, 106, 106)
                                        .addComponent(vehicleAvailabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(whiteAreaLayout.createSequentialGroup()
                                        .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hourlyRateTxt)
                                            .addComponent(dailyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, whiteAreaLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        whiteAreaLayout.setVerticalGroup(
            whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whiteAreaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDeleteButton))
                .addGap(18, 18, 18)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vehicleNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(capacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentMilateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dailyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleAvailabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(36, 36, 36)
                .addGroup(whiteAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout contentAreaLayout = new javax.swing.GroupLayout(contentArea);
        contentArea.setLayout(contentAreaLayout);
        contentAreaLayout.setHorizontalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(whiteArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        contentAreaLayout.setVerticalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(whiteArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(contentArea);

        exitButton.setOpaque(false);

        exitButtonLable.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        exitButtonLable.setForeground(new java.awt.Color(255, 255, 255));
        exitButtonLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButtonLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/close.png"))); // NOI18N
        exitButtonLable.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        exitButtonLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonLableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitButtonLayout.createSequentialGroup()
                .addContainerGap(825, Short.MAX_VALUE)
                .addComponent(exitButtonLable)
                .addGap(10, 10, 10))
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(exitButtonLable)
                .addContainerGap(609, Short.MAX_VALUE))
        );

        jLayeredPane1.add(exitButton);

        backButton.setOpaque(false);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/back.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout backButtonLayout = new javax.swing.GroupLayout(backButton);
        backButton.setLayout(backButtonLayout);
        backButtonLayout.setHorizontalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblBack)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        backButtonLayout.setVerticalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblBack)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jLayeredPane1.add(backButton);

        blueStrip.setOpaque(false);

        lblBlueStrip.setBackground(new java.awt.Color(52, 73, 94));
        lblBlueStrip.setOpaque(true);

        javax.swing.GroupLayout blueStripLayout = new javax.swing.GroupLayout(blueStrip);
        blueStrip.setLayout(blueStripLayout);
        blueStripLayout.setHorizontalGroup(
            blueStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueStripLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblBlueStrip, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        blueStripLayout.setVerticalGroup(
            blueStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueStripLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblBlueStrip, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jLayeredPane1.add(blueStrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonLableMouseClicked
        close();
    }//GEN-LAST:event_exitButtonLableMouseClicked

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") == JOptionPane.OK_OPTION) {
            new TMS_manageVehicles().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblBackMouseReleased

    private void lblAddButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddButtonMouseReleased
        String query = "INSERT INTO `fnss`.`tms_hirevehicle`\n"
                + "(`vehicleRegNo`, `type`, `capacity`, `milage`, `hourlyRate`, `dailyRate`)\n"
                + "VALUES\n"
                + "('" + vehicleNumberTxt.getText() + "', "
                + "'" + typeComboBox.getSelectedItem().toString()+ "', "
                + "" + capacityTxt.getText() + ","
                + "" + currentMilateTxt.getText() + ", "
                + "" + hourlyRateTxt.getText() + ","
                + "" + dailyRateTxt.getText() + ");";

        try {
            DB.getDbCon().insert(query);

            if (JOptionPane.showConfirmDialog(null, "Proceed?") == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "New Vehicle Saved!");
                new TMS_manageVehicles().setVisible(true);
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblAddButtonMouseReleased

    private void lblUpdateButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateButtonMouseReleased
        String query = "UPDATE `fnss`.`tms_hirevehicle`\n"
                + "SET\n"
                + "`type` = '" + typeComboBox.getSelectedItem().toString()+ "',\n"
                + "`capacity` = " + capacityTxt.getText() + ",\n"
                + "`milage` = " + currentMilateTxt.getText() + ",\n"
                + "`hourlyRate` = " + hourlyRateTxt.getText() + ",\n"
                + "`dailyRate` = " + dailyRateTxt.getText() + "\n"
                + "WHERE `vehicleRegNo` = '" + vehicleNumberTxt.getText() + "';";

        try {
            DB.getDbCon().insert(query);

            if (JOptionPane.showConfirmDialog(null, "Proceed?") == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "Vehicle Updated!");
                new TMS_manageVehicles().setVisible(true);
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblUpdateButtonMouseReleased

    private void lblDeleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteButtonMouseReleased

        String query = "DELETE FROM `fnss`.`tms_hirevehicle`\n"
                + "WHERE `vehicleRegNo` = '" + vehicleNumberTxt.getText() + "'";

        try {
            DB.getDbCon().insert(query);

            if (JOptionPane.showConfirmDialog(null, "Confirm Delete Vehicle?") == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "Vehicle Successfully Deleted!");
                new TMS_manageVehicles().setVisible(true);
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblDeleteButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TMS_addUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMS_addUpdateVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backButton;
    private javax.swing.JPanel blueStrip;
    public javax.swing.JTextField capacityTxt;
    private javax.swing.JPanel contentArea;
    public javax.swing.JTextField currentMilateTxt;
    public javax.swing.JTextField dailyRateTxt;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitButtonLable;
    private javax.swing.JPanel functionImage;
    public javax.swing.JTextField hourlyRateTxt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAddButton;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBlueStrip;
    private javax.swing.JLabel lblDeleteButton;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblUpdateButton;
    public javax.swing.JComboBox<String> typeComboBox;
    public javax.swing.JTextField vehicleAvailabilityTxt;
    public javax.swing.JTextField vehicleNumberTxt;
    private javax.swing.JPanel whiteArea;
    // End of variables declaration//GEN-END:variables
}
