/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inv.gui;

import com.sun.glass.events.KeyEvent;
import fnss.functions.DB;
import fnss.functions.DocNumGenerator;
import fnss.test.TestDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sachini
 */
public class NewOrder extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    public NewOrder() {
        initComponents();
        this.setLocationRelativeTo(null);
        
          Date now = new Date();
        //Set date format as you want
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd"); 
        txtdate.setText(sf.format(now));
          try {
            txtoID.setText((new DocNumGenerator().curVal("ORD")));
            txtoID.setText((new DocNumGenerator().nextVal("ORD")));
        } catch (SQLException ex) {
            Logger.getLogger(TestDB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
           try{
     String cat="SELECT SupplierName FROM Supplier where Active=1";
       ResultSet rs=DB.getDbCon().query(cat);
       while(rs.next())
       {
           cmbSup.addItem(rs.getString("SupplierName"));
       }
}
catch(Exception e)
{

}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblneworder = new javax.swing.JTable();
        txtoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIcode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQtyI = new javax.swing.JTextField();
        cmbunits = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        newOrdersearch = new javax.swing.JLabel();
        txtNewOrderSearch = new javax.swing.JTextField();
        cmbSup = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 660));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(950, 660));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(950, 660));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 140, 50));

        lblUser.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/close.png"))); // NOI18N
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inv/gui/back (3).png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(127, 140, 141));
        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));

        tblneworder.setBackground(new java.awt.Color(52, 73, 94));
        tblneworder.setForeground(new java.awt.Color(255, 255, 255));
        tblneworder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Code", "Item Name"
            }
        ));
        tblneworder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblneworderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblneworderMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblneworder);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 840, 180));
        jPanel2.add(txtoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 170, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Supplier");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 20));
        jPanel2.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 280, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("User");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 280, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Description");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel2.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 640, 50));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Item Code");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
        jPanel2.add(txtIcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Qty");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        txtQtyI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyIKeyTyped(evt);
            }
        });
        jPanel2.add(txtQtyI, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 190, -1));

        cmbunits.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Units", "Gallons", "Liters", "Kilos" }));
        jPanel2.add(cmbunits, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jLabel9.setBackground(new java.awt.Color(52, 73, 94));
        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Proceed");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 120, 30));

        newOrdersearch.setBackground(new java.awt.Color(52, 73, 94));
        newOrdersearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        newOrdersearch.setForeground(new java.awt.Color(255, 255, 255));
        newOrdersearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newOrdersearch.setText("Search");
        newOrdersearch.setOpaque(true);
        newOrdersearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrdersearchMouseClicked(evt);
            }
        });
        jPanel2.add(newOrdersearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, 30));
        jPanel2.add(txtNewOrderSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, 30));

        cmbSup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jPanel2.add(cmbSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 950, 540));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        close();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        new OrderManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtQtyIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyIKeyTyped
        char c = evt.getKeyChar();
         if(!((Character.isDigit(c)) || (c==KeyEvent.VK_BACKSPACE) 
               || (c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtQtyIKeyTyped

    private void newOrdersearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrdersearchMouseClicked
        String srch=new String(txtNewOrderSearch.getText());
        String sql="SELECT ItemCode, ItemName  FROM `stock` where ItemName LIKE '%"+srch+"%'";
        try
        {
        ResultSet rs=DB.getDbCon().query(sql);
        tblneworder.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_newOrdersearchMouseClicked

    private void tblneworderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblneworderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblneworderMouseEntered

    private void tblneworderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblneworderMouseClicked
        txtIcode.setText(tblneworder.getValueAt(tblneworder.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tblneworderMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        String icode=new String(txtIcode.getText());
        String orderID=new String(txtoID.getText());
        String date=new String(txtdate.getText());
        String user=new String(txtUser.getText());
        String desc=new String(txtDesc.getText());
        String qty=new String(txtQtyI.getText());
        String sup=String.valueOf(cmbSup.getSelectedItem());
        String unit=String.valueOf(cmbunits.getSelectedItem());
        
        
        String sql="INSERT INTO `order` values('"+orderID+"','"+qty+"','"+sup+"','"+desc+"','"+icode+"','"+unit+"','"+date+"','"+user+"','0')";
         try{
       DB.getDbCon().insert(sql);
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
         
         txtDesc.setText("");
         txtIcode.setText("");
         txtQtyI.setText("");
         txtUser.setText("");
         txtdate.setText("");
         txtoID.setText("");
         cmbSup.setSelectedIndex(0);
         cmbunits.setSelectedIndex(0);
          String s="Added successfully";
        JOptionPane.showMessageDialog(null,s);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSup;
    private javax.swing.JComboBox cmbunits;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel newOrdersearch;
    private javax.swing.JTable tblneworder;
    private javax.swing.JTextField txtDesc;
    public javax.swing.JTextField txtIcode;
    private javax.swing.JTextField txtNewOrderSearch;
    private javax.swing.JTextField txtQtyI;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtoID;
    // End of variables declaration//GEN-END:variables
private void close() {
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") == JOptionPane.OK_OPTION) {
            this.dispose();
        }
 }


}
