/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inv.gui;

/**
 *
 * @author Sachini
 */
public class NewOrder extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    public NewOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtOrderID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOrderItemCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOrderQty = new javax.swing.JTextField();
        Units = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblProceedOrder = new javax.swing.JLabel();
        cmbSupplierSearch = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOrderDesc = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        lblMinutes = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        lblSearchNewOrder = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblBackgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1083, 610));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 230, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/search.png"))); // NOI18N
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 168, -1, 22));

        txtOrderItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderItemCodeActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txtOrderItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/search.png"))); // NOI18N
        jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 349, -1, -1));
        jDesktopPane1.add(txtOrderQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 180, 50));

        Units.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Unit", "Item 2", "Item 3", "Item 4" }));
        jDesktopPane1.add(Units, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 660, 160));

        lblProceedOrder.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProceedOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(lblProceedOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 554, 180, 40));

        cmbSupplierSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supplier" }));
        jDesktopPane1.add(cmbSupplierSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 230, 40));

        txtOrderDesc.setColumns(20);
        txtOrderDesc.setRows(5);
        txtOrderDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(txtOrderDesc);

        jDesktopPane1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 660, 50));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jDesktopPane1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 80, 50));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jDesktopPane1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 90, 50));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jDesktopPane1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 100, 50));
        jDesktopPane1.add(lblMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 70, 40));
        jDesktopPane1.add(lblHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 70, 40));
        jDesktopPane1.add(lblSearchNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 50, 40));
        jDesktopPane1.add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 276, 50, 40));

        lblBackgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/gui/newOrder1.jpg"))); // NOI18N
        lblBackgound.setText("jLabel15");
        lblBackgound.setMaximumSize(new java.awt.Dimension(1083, 610));
        lblBackgound.setMinimumSize(new java.awt.Dimension(1083, 610));
        jDesktopPane1.add(lblBackgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 1090, 610));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderItemCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Units;
    private javax.swing.JComboBox cmbSupplierSearch;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBackgound;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblProceedOrder;
    private javax.swing.JLabel lblSearchNewOrder;
    private javax.swing.JTextArea txtOrderDesc;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtOrderItemCode;
    private javax.swing.JTextField txtOrderQty;
    // End of variables declaration//GEN-END:variables
}
