/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inv.gui;

import fnss.functions.DB;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sachini
 */
public class OrderRecieving extends javax.swing.JFrame {

    /**
     * Creates new form OrderRecieving
     */
    public OrderRecieving() {
        initComponents();
        this.setLocationRelativeTo(null);
        Date now = new Date();
        //Set date format as you want
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd"); 
        txtOrderRDate.setText(sf.format(now));
        String itmc=new String(txtOrdItm.getText());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtOrderRID = new javax.swing.JTextField();
        txtOrderRSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrderRDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOrdItm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtunit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        unitprice = new javax.swing.JTextField();
        txtTot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(940, 528));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(940, 528));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Order Recieving");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 28, 287, 39));

        lblUser.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnss/images/close.png"))); // NOI18N
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inv/gui/back (3).png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 40));

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        jPanel2.setBackground(new java.awt.Color(236, 240, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
        jLabel2.setText("Order ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 50, 88, -1));
        jPanel2.add(txtOrderRID, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 50, 133, -1));

        txtOrderRSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderRSupplierActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrderRSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 133, 133, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
        jLabel3.setText("Supplier");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 133, -1, -1));

        txtOrderRDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderRDateActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrderRDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 137, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
        jLabel4.setText("Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 62, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
        jLabel5.setText("Total");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 373, -1, -1));

        jLabel8.setBackground(new java.awt.Color(52, 73, 94));
        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Proceed");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 367, 116, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Item Code");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 135, -1, -1));
        jPanel2.add(txtOrdItm, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 133, 138, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 228, -1, -1));
        jPanel2.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Unit");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));
        jPanel2.add(txtunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 80, -1));

        jLabel10.setText("Unit Price");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));
        jPanel2.add(unitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 140, -1));
        jPanel2.add(txtTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 230, -1));

        jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 940, 520));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderRSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderRSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderRSupplierActionPerformed

    private void txtOrderRDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderRDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderRDateActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        close();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        new OrderManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    String oid=new String(txtOrderRID.getText());
    String date=new String(txtOrderRDate.getText());
    String Total=new String(txtTot.getText());
    String itm=new String(txtOrdItm.getText());
    String qt=new String(txtqty.getText());
        String sql1="Select Quantity from `stock` where ItemCode='"+itm+"'";
        int q = 0;
        try
        {
        
        ResultSet rs=DB.getDbCon().query(sql1);
        while(rs.next())
        {
         q=Integer.parseInt(rs.getString("Quantity"));
        
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        int quantity=Integer.parseInt(qt);
        q=q+quantity;
        
        String sql2="UPDATE `stock` SET Quantity='"+q+"' where ItemCode='"+itm+"'";
        try
        {
        DB.getDbCon().insert(sql2);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
       
        String sql="INSERT INTO `orderecieve` (OrderID,Date,Total)values ('"+oid+"','"+date+"','"+Total+"')";
        try
        {
        DB.getDbCon().insert(sql);
        String s="Added successfully";
        JOptionPane.showMessageDialog(null,s);
        }
        catch(Exception e)
        {
            System.out.println(e);
        
        }
        
         String sql3="UPDATE `order` SET Status=1 where OrderID='"+oid+"'";
         try
         {
         DB.getDbCon().insert(sql3);
         }
         catch(Exception e)
         {
             System.out.println(e);
         }
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderRecieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderRecieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderRecieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderRecieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderRecieving().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblUser;
    public javax.swing.JTextField txtOrdItm;
    private javax.swing.JTextField txtOrderRDate;
    public javax.swing.JTextField txtOrderRID;
    public javax.swing.JTextField txtOrderRSupplier;
    public javax.swing.JTextField txtTot;
    public javax.swing.JTextField txtqty;
    public javax.swing.JTextField txtunit;
    public javax.swing.JTextField unitprice;
    // End of variables declaration//GEN-END:variables
private void close() {
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") == JOptionPane.OK_OPTION) {
            this.dispose();
        }
 }

}
